### ISSUE TITLE
Consider creating an organization for the project

### ISSUE THREAD

**Issue by Sytten** [graphql-query-rewriter/graphql-query-rewriter#28]
I would like to see the community around the "One schema never breaking" grow and be adopted more widely. I think that will require more plugins and a community managed roadmap. I think it would be good as a first step to create an Organization for the project and regroup plugins there like the express one and apollo #27. Then they can be moved under the same prefix in npm.

**Comment by Sytten** [comment]
I am also planning on contributing a few rewriter and probably on the rewrite needed to support #26

**Comment by chanind** [comment]
This is a great suggestion, it would certainly make things easier to manage as its own org. I just want to confirm with some coworkers that it's OK first. What would make sense as an org name? `graphql-query-rewriter`?

**Comment by Sytten** [comment]
Good question, that seems like a good name

**Comment by chanind** [comment]
I just got the OK to move this to an org, we'll just have to say something like `Sponsored by EF Hello` in the bottom of the readme. I'll get this set up and moved over tomorrow, and add you as a collaborator

**Comment by Sytten** [comment]
Super! Do you also want to create the npm organization? I want to start moving packages under a common name and publish the apollo integrations.

**Comment by chanind** [comment]
Apologies for the delay! The new org is set up. I registered the npm org as well but haven't done the swap yet.

**Comment by Sytten** [comment]
any news @chanind ?

**Comment by chanind** [comment]
On the Github org front, that should be good to go. You should be added as a member, so if you want to make a repo for the apollo integration definitely feel free! On the npm org side, I made the org, but I can't figure out how to move the npm packages under the org without causing them to change their name on npm (`graphql-query-rewriter` -> `@graphql-query-rewriter/graphql-query-rewriter`, seems sort of redundant).

**Comment by Sytten** [comment]
Right, we either call it `@graphql-query-rewriter/core` (or something similar) or stick with the current name. Maybe run it by the team to get some ideas. I will work on the apollo integration. I received an invite for the npm org but I cant seem to able to accept it.

**Comment by chanind** [comment]
Just resent the npm invite. True, `@graphql-query-rewriter/core` seems pretty reasonable. If we go that route, probably makes sense to rename this repo as well
